version: "3.7"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'clippings'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: